version: "2"
services:
  cassandra:
    hostname: cassandra
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"

    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports:
      - "9042:9042"
      - "9160:9160"
      # CASSANDRA_LISTEN_ADDRESS:
    # volumes: # uncomment if you desire mounts, also uncomment cluster.sh
    #   - ./data/cassandra-1:/var/lib/cassandra:rw

  web:

    depends_on:
      - cassandra
    links:
      - cassandra:cassandra

    build: .

    # Unkown if this will effect hot loading
    # volumes:
    #   - "./app:/src/app"
    ports:
      - "3000:3000"
