version: "2"
services:
  cassandra:
    hostname: cassandra
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && /docker-entrypoint.sh cassandra -f"

    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports:
      - "9042:9042"
      - "9160:9160"

  setupcassandra:
    build: cassandra-docker
    depends_on:
      - cassandra
    links:
      - cassandra:cassandra
    command: bash -c "sleep 45 && echo Creating keyspace and tables && cqlsh cassandra -f init.cql && sleep infinity"


  web:

    depends_on:
      - cassandra
    links:
      - cassandra:cassandra

    build: express-docker

    ports:
      - "80:3000"
